### ISSUE TITLE
Get the file system set up

### ISSUE THREAD

**Issue by bradonladd** [Reece-Reklai/DormitoryWasherAndDryer#1]
Something that I used in my summer project was the split betwen the view and the model portion. In other words, "lib" was split into two folders, "view" and "model". Anything UI related went into "view" and anything system related went into "model". They were bridged by header files (labelled as view.dart and model.dart respectively) that could be imported by either section. Here's an example:

lib
- | view
- - | view.dart
- - | uithing.dart
- | model
- - | model.dart
- - | classthing.dart

Then, if, say, "uithing.dart" needed something from "classthing.dart", "uithing.dart" would import like this: 

import "../model/model.dart"

This way the UI and the system are separated and treated like packages, essentially. I will be branching and setting this up.

**Comment by MatijaBenko** [comment]
Great suggestion, we will account when building out the layout
